"""set username unique

Revision ID: 60e7ccbcc5fc
Revises: 412dfa8002f2
Create Date: 2023-04-03 22:53:51.750044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e7ccbcc5fc'
down_revision = '412dfa8002f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'], schema='auth')
    op.create_unique_constraint(None, 'user', ['username'], schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='auth', type_='unique')
    op.drop_constraint(None, 'user', schema='auth', type_='unique')
    # ### end Alembic commands ###
